version: '3.2'
services:

  ifts12-db:
    container_name: 'ifts12-db'
    image: 'mysql'
    volumes:
      - './mysql:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password --sql_mode='''
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ifts12'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    env_file:
      - '.env'
  ifts12-api:
    depends_on:
      - 'ifts12-db'
    container_name: 'ifts12-api'
    image: 'node'
    volumes:
      - '.:/var/www/html'
    ports:
      - '4006:4000'
    tty: true
    working_dir: '/var/www/html'
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    env_file:
      - '.env'
    command: 'bash -c "yarn && yarn dev"'
    # command: bash -c "yarn && yarn build && yarn prod"
    # restart: always
