version: '3'
services:
    ifts12-db:
        container_name: ifts12-db
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: itm
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    ifts12-api:
        depends_on: 
            - ifts12-db
        container_name: ifts12-api
        image: node
        volumes: 
            - .:/var/www/html
        ports:  
            - ${APP_PORT}:3000
        # command: bash -c "yarn && yarn build && yarn prod"
        tty: true
        working_dir: /var/www/html
        env_file: 
            - .env
